# Generated by Django 4.0.3 on 2022-03-23 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_profile', models.ImageField(default='page_profile_default.jpeg', upload_to='page_profile')),
                ('page_title', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField()),
                ('field', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('your_role', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=10)),
                ('linkdin_profile_link', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('page_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_posts')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admin_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_post', to='pages.page')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_post_like', to='pages.pagepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_post_user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_page_post', to='pages.pagepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_page_post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
